name: TypeScript Compilation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    
    - name: Install dependencies
      run: |
        npm init -y
        npm install typescript
    
    - name: Compile TypeScript
      run: |
        npx tsc
    
    - name: Commit compiled JS
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add scripts/main.js
        git commit -m "Add compiled JavaScript" || echo "No changes to commit"
        git push
