name: TypeScript Compilation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    
    - name: Install dependencies
      run: |
        npm init -y
        npm install typescript
    
    - name: Debug TypeScript files
      run: |
        echo "TypeScript files in src:"
        ls -R src/
        echo "Current tsconfig.json:"
        cat tsconfig.json
    
    - name: Compile TypeScript
      run: |
        mkdir -p scripts
        npx tsc --project tsconfig.json
    
    - name: Debug compilation output
      run: |
        echo "Compiled files in scripts:"
        ls -la scripts/
    
    - name: Commit and push if changed
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add scripts/
        git commit -m "Add compiled JavaScript" || echo "No changes to commit"
        git push || echo "No changes to push"
