name: TypeScript Compilation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    
    - name: Install dependencies
      run: |
        npm init -y
        npm install typescript
    
    - name: Create scripts directory and compile
      run: |
        mkdir -p scripts
        npx tsc --project tsconfig.json
    
    - name: Debug output
      run: |
        echo "Contents of scripts directory:"
        ls -la scripts/
    
    - name: Commit and push
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add scripts/main.js
        git commit -m "Add compiled JavaScript" || echo "No changes to commit"
        git push origin main || echo "No changes to push"
